# Generated by Django 2.2.19 on 2022-09-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_surbscribed',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
