# Generated by Django 2.2.16 on 2022-10-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221012_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('author', 'follower')},
        ),
    ]
