# Generated by Django 2.2.19 on 2022-12-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20221124_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_surbscribed',
            new_name='is_subscribed',
        ),
    ]
