# Generated by Django 2.2.16 on 2022-09-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('measurment_unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('is_favorited', models.BooleanField()),
                ('is_in_shopping_cart', models.BooleanField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('cooking_time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
