# Generated by Django 2.2.19 on 2022-09-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220911_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeIngredientAdmin',
            fields=[
                ('recipeingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.RecipeIngredient')),
            ],
            bases=('api.recipeingredient',),
        ),
        migrations.CreateModel(
            name='RecipeTagAdmin',
            fields=[
                ('recipetag_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.RecipeTag')),
            ],
            bases=('api.recipetag',),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredients')},
        ),
    ]
