# Generated by Django 2.2.19 on 2022-09-11 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220911_1817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipetag',
            unique_together={('recipe', 'tag')},
        ),
    ]
