# Generated by Django 2.2.19 on 2022-09-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220916_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartAdmin',
            fields=[
                ('shoppingcart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ShoppingCart')),
            ],
            bases=('api.shoppingcart',),
        ),
    ]
