# Generated by Django 2.2.19 on 2022-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_shoppingcartadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
