# Generated by Django 2.2.16 on 2022-10-17 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20221015_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_tags', to='api.Tag'),
        ),
    ]
