# Generated by Django 2.2.19 on 2022-11-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20221127_1215'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipetag',
            name='unique_tag_in_recipe',
        ),
    ]
